RESTAURANTS = [
    {
        "id": "1",
        "name": "The Spice Garden",
        "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
        "cuisine": ["Indian", "North Indian"],
        "rating": 4.5,
        "deliveryTime": "25-35 min",
        "priceRange": "$$",
        "distance": "1.2 km",
        "featured": True,
        "menu": [
            {
                "id": "1-1",
                "name": "Butter Chicken",
                "description": "Creamy tomato-based curry with tender chicken",
                "price": 14.99,
                "image": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": False,
                "isBestseller": True,
            },
            {
                "id": "1-2",
                "name": "Paneer Tikka",
                "description": "Grilled cottage cheese with spices",
                "price": 11.99,
                "image": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&h=200&fit=crop",
                "category": "Starters",
                "isVeg": True,
                "isBestseller": True,
            },
            {
                "id": "1-3",
                "name": "Dal Makhani",
                "description": "Slow-cooked black lentils in creamy gravy",
                "price": 9.99,
                "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": True,
            },
            {
                "id": "1-4",
                "name": "Garlic Naan",
                "description": "Freshly baked bread with garlic butter",
                "price": 3.49,
                "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=300&h=200&fit=crop",
                "category": "Breads",
                "isVeg": True,
            },
            {
                "id": "1-5",
                "name": "Gulab Jamun",
                "description": "Deep-fried milk dumplings in sugar syrup",
                "price": 5.99,
                "image": "https://images.unsplash.com/photo-1666190070119-a75e5023cf78?w=300&h=200&fit=crop",
                "category": "Desserts",
                "isVeg": True,
            },
            {
                "id": "1-6",
                "name": "Chicken Biryani",
                "description": "Fragrant basmati rice with spiced chicken",
                "price": 15.99,
                "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": False,
                "isBestseller": True,
            },
        ],
    },
    {
        "id": "2",
        "name": "Pizza Paradise",
        "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
        "cuisine": ["Italian", "Pizza"],
        "rating": 4.3,
        "deliveryTime": "20-30 min",
        "priceRange": "$$",
        "distance": "0.8 km",
        "featured": True,
        "menu": [
            {
                "id": "2-1",
                "name": "Margherita Pizza",
                "description": "Classic pizza with mozzarella and basil",
                "price": 12.99,
                "image": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=300&h=200&fit=crop",
                "category": "Pizza",
                "isVeg": True,
                "isBestseller": True,
            },
            {
                "id": "2-2",
                "name": "Pepperoni Pizza",
                "description": "Loaded with spicy pepperoni and cheese",
                "price": 14.99,
                "image": "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=300&h=200&fit=crop",
                "category": "Pizza",
                "isVeg": False,
            },
            {
                "id": "2-3",
                "name": "Caesar Salad",
                "description": "Crisp romaine with parmesan and croutons",
                "price": 8.99,
                "image": "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=300&h=200&fit=crop",
                "category": "Starters",
                "isVeg": True,
            },
            {
                "id": "2-4",
                "name": "Tiramisu",
                "description": "Italian coffee-flavored layered dessert",
                "price": 7.99,
                "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300&h=200&fit=crop",
                "category": "Desserts",
                "isVeg": True,
            },
            {
                "id": "2-5",
                "name": "Pasta Carbonara",
                "description": "Creamy pasta with bacon and parmesan",
                "price": 13.99,
                "image": "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=300&h=200&fit=crop",
                "category": "Pasta",
                "isVeg": False,
                "isBestseller": True,
            },
        ],
    },
    {
        "id": "3",
        "name": "Sushi Sensation",
        "image": "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600&h=400&fit=crop",
        "cuisine": ["Japanese", "Sushi"],
        "rating": 4.7,
        "deliveryTime": "30-40 min",
        "priceRange": "$$$",
        "distance": "2.5 km",
        "menu": [
            {
                "id": "3-1",
                "name": "California Roll",
                "description": "Crab, avocado, and cucumber roll",
                "price": 11.99,
                "image": "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=300&h=200&fit=crop",
                "category": "Sushi Rolls",
                "isVeg": False,
                "isBestseller": True,
            },
            {
                "id": "3-2",
                "name": "Salmon Nigiri",
                "description": "Fresh salmon over pressed rice",
                "price": 9.99,
                "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=300&h=200&fit=crop",
                "category": "Nigiri",
                "isVeg": False,
            },
            {
                "id": "3-3",
                "name": "Edamame",
                "description": "Steamed soybeans with sea salt",
                "price": 5.99,
                "image": "https://images.unsplash.com/photo-1564093497595-593b96d80571?w=300&h=200&fit=crop",
                "category": "Starters",
                "isVeg": True,
            },
            {
                "id": "3-4",
                "name": "Miso Soup",
                "description": "Traditional Japanese soybean soup",
                "price": 4.99,
                "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=300&h=200&fit=crop",
                "category": "Soups",
                "isVeg": True,
            },
            {
                "id": "3-5",
                "name": "Mochi Ice Cream",
                "description": "Japanese rice cake filled with ice cream",
                "price": 6.99,
                "image": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=300&h=200&fit=crop",
                "category": "Desserts",
                "isVeg": True,
            },
        ],
    },
    {
        "id": "4",
        "name": "Burger Barn",
        "image": "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop",
        "cuisine": ["American", "Burgers"],
        "rating": 4.1,
        "deliveryTime": "15-25 min",
        "priceRange": "$",
        "distance": "0.5 km",
        "featured": True,
        "menu": [
            {
                "id": "4-1",
                "name": "Classic Cheeseburger",
                "description": "Beef patty with cheddar, lettuce, and tomato",
                "price": 9.99,
                "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop",
                "category": "Burgers",
                "isVeg": False,
                "isBestseller": True,
            },
            {
                "id": "4-2",
                "name": "Crispy Chicken Burger",
                "description": "Fried chicken with slaw and pickles",
                "price": 10.99,
                "image": "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=300&h=200&fit=crop",
                "category": "Burgers",
                "isVeg": False,
            },
            {
                "id": "4-3",
                "name": "Loaded Fries",
                "description": "Fries topped with cheese, bacon, and jalapeños",
                "price": 7.99,
                "image": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300&h=200&fit=crop",
                "category": "Sides",
                "isVeg": False,
            },
            {
                "id": "4-4",
                "name": "Chocolate Milkshake",
                "description": "Thick and creamy chocolate shake",
                "price": 5.99,
                "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=300&h=200&fit=crop",
                "category": "Drinks",
                "isVeg": True,
            },
            {
                "id": "4-5",
                "name": "Veggie Burger",
                "description": "Plant-based patty with all the fixings",
                "price": 10.99,
                "image": "https://images.unsplash.com/photo-1520072959219-c595e6cdc07a?w=300&h=200&fit=crop",
                "category": "Burgers",
                "isVeg": True,
            },
        ],
    },
    {
        "id": "5",
        "name": "Thai Orchid",
        "image": "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&h=400&fit=crop",
        "cuisine": ["Thai", "Asian"],
        "rating": 4.4,
        "deliveryTime": "30-45 min",
        "priceRange": "$$",
        "distance": "3.0 km",
        "menu": [
            {
                "id": "5-1",
                "name": "Pad Thai",
                "description": "Stir-fried rice noodles with shrimp and peanuts",
                "price": 13.99,
                "image": "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": False,
                "isBestseller": True,
            },
            {
                "id": "5-2",
                "name": "Green Curry",
                "description": "Coconut-based curry with Thai basil",
                "price": 14.99,
                "image": "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": False,
            },
            {
                "id": "5-3",
                "name": "Spring Rolls",
                "description": "Crispy vegetable spring rolls",
                "price": 6.99,
                "image": "https://images.unsplash.com/photo-1548507200-e9e0e7e2e8d1?w=300&h=200&fit=crop",
                "category": "Starters",
                "isVeg": True,
            },
            {
                "id": "5-4",
                "name": "Tom Yum Soup",
                "description": "Spicy and sour Thai soup",
                "price": 7.99,
                "image": "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=300&h=200&fit=crop",
                "category": "Soups",
                "isVeg": False,
            },
            {
                "id": "5-5",
                "name": "Mango Sticky Rice",
                "description": "Sweet sticky rice with fresh mango",
                "price": 8.99,
                "image": "https://images.unsplash.com/photo-1621293954908-907159247fc8?w=300&h=200&fit=crop",
                "category": "Desserts",
                "isVeg": True,
            },
        ],
    },
    {
        "id": "6",
        "name": "Mediterranean Bites",
        "image": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
        "cuisine": ["Mediterranean", "Greek"],
        "rating": 4.6,
        "deliveryTime": "25-35 min",
        "priceRange": "$$",
        "distance": "1.8 km",
        "menu": [
            {
                "id": "6-1",
                "name": "Falafel Wrap",
                "description": "Crispy falafel with tahini and veggies",
                "price": 10.99,
                "image": "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=300&h=200&fit=crop",
                "category": "Wraps",
                "isVeg": True,
                "isBestseller": True,
            },
            {
                "id": "6-2",
                "name": "Chicken Shawarma",
                "description": "Marinated chicken with garlic sauce",
                "price": 12.99,
                "image": "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=300&h=200&fit=crop",
                "category": "Main Course",
                "isVeg": False,
                "isBestseller": True,
            },
            {
                "id": "6-3",
                "name": "Hummus & Pita",
                "description": "Creamy hummus with warm pita bread",
                "price": 7.99,
                "image": "https://images.unsplash.com/photo-1637949385162-e416fb15b68b?w=300&h=200&fit=crop",
                "category": "Starters",
                "isVeg": True,
            },
            {
                "id": "6-4",
                "name": "Greek Salad",
                "description": "Feta, olives, tomatoes, and cucumbers",
                "price": 9.99,
                "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=300&h=200&fit=crop",
                "category": "Salads",
                "isVeg": True,
            },
            {
                "id": "6-5",
                "name": "Baklava",
                "description": "Layered pastry with nuts and honey",
                "price": 6.99,
                "image": "https://images.unsplash.com/photo-1598110750624-207050c4f28c?w=300&h=200&fit=crop",
                "category": "Desserts",
                "isVeg": True,
            },
        ],
    },
]
